# Basic Site Settings
locale: "en-US"
site_theme: "default"
title: "Taewoo Kim | Computational Imaging & Generative AI"
title_separator: "-"
name: &name "Taewoo Kim"
description: &description "Senior Research Engineer at Qualcomm Korea, specializing in computational imaging, event-based vision, and generative AI."
url: "https://taewook.github.io"
baseurl: ""
repository: "taewookpro/taewook.github.io"

# Site Author
author:
  avatar: "profile.jpg"
  name: "Taewoo Kim"
  bio: "Senior Research Engineer at Qualcomm Korea. Interested in event-based vision, computational imaging, and generative AI."
  location: "Seoul, South Korea"
  employer: "Qualcomm Korea"
  email: "taewook@example.com"

  # Academic profiles
  googlescholar: "https://scholar.google.com/citations?hl=en&user=SzKw5oYAAAAJ"
  github: "taewookpro"
  linkedin: "taewoo-kim"

# Publication Categories
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# Other Site Settings
teaser:
breadcrumbs: false
words_per_minute: 160
future: true
read_more: "disabled"
talkmap_link: false

# Comments (disabled)
comments:
  provider: false

# Analytics (optional)
analytics:
  provider: false

# Output / Build
timezone: "Asia/Seoul"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji
